Select ID_PRODUCTO, NOMBRE, DESCRIPCION, STOCK_MINIMO, STOCK_MAXIMO, ID_USUARIO_CREADOR, FECHA_CREACION, ESTADO, STOCK from TAD_SHOP.PRODUCTO
USE TAD_SHOP;

CREATE TABLE `PRODUCTO` (
  `ID_PRODUCTO` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(45) DEFAULT NULL,
  `DESCRIPCION` varchar(45) DEFAULT NULL,
  `STOCK_MINIMO` int(11) DEFAULT NULL,
  `STOCK_MAXIMO` int(11) DEFAULT NULL,
  `ID_USUARIO_CREADOR` int(11) DEFAULT NULL,
  `FECHA_CREACION` datetime DEFAULT NULL,
  `ESTADO` varchar(45) DEFAULT NULL,
  `STOCK` int(11) DEFAULT '0',
  PRIMARY KEY (`ID_PRODUCTO`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=latin1;


insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (1,'revista','prueba',10,500,1,'2020-12-14 18:50:36','"B"',300);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (2,'revista','prueba',10,500,1,'2020-12-14 18:51:37','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (3,'vaso','baso batman ',1,10,1,'2020-12-14 18:51:38','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (6,'remera','remera',5,50,1,'2020-12-14 20:51:17','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (7,'aaa','sss',33,66,1,'2020-12-14 20:51:45','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (8,'borrador','es el que borro',10,30,1,'2020-12-14 21:52:30','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (9,'borrar2','borrar2',10,50,1,'2020-12-14 21:53:02','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (10,'prueba3','prueba3',10,900,1,'2020-12-14 21:58:21','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (11,'peste','asd',11,2222,1,'2020-12-14 22:14:30','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (12,'asd asdasdasdasdsa','wer',55,55555,1,'2020-12-14 22:14:39','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (13,'werwerewr','werwer we w rwe rwe rew rwe',222,4444,1,'2020-12-14 22:15:07','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (14,'asd','ddddd',null,null,1,'2020-12-14 22:15:49','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (15,'asd asdasdasdasdsa','aa',null,null,1,'2020-12-14 23:25:51','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (16,'para borrar','asd',3324,223334,1,'2020-12-15 18:15:14','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (17,'bubu','asdas sad sada',22,5000,1,'2020-12-15 18:16:59','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (18,'noni','asd',333,44444,1,'2020-12-15 18:17:11','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (19,'nose','wq',0,100,1,'2020-12-15 18:17:21','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (20,'qqqqqq','asdasd',0,999,1,'2020-12-15 19:54:37','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (21,'qqq2','asd',0,88888,1,'2020-12-15 19:55:10','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (22,'asd asdasdasdasdsa','inicial',1,11,1,'2020-12-16 12:05:49','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (23,'qqq2www','prueba final',10,5362,1,'2020-12-16 12:06:34','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (24,null,null,null,null,1,'2020-12-16 18:38:07','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (25,'nuevo libro','libro ',2,500,1,'2020-12-16 21:40:18','"B"',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (26,'movil1','movil1',10,500,1,'2020-12-17 11:37:03','A',48);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (27,'movil2','movil2',10,500,1,'2020-12-17 11:37:26','A',0);
insert into `PRODUCTO`(`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`STOCK_MINIMO`,`STOCK_MAXIMO`,`ID_USUARIO_CREADOR`,`FECHA_CREACION`,`ESTADO`,`STOCK`) values (28,'movil3','movil3',10,500,1,'2020-12-17 11:37:49','A',0);
