Select ID_USUARIO, NOMBRE, APELLIDO, NOMBRE_APODO, PASS, ESTADO from TAD_SHOP.USUARIO
USE TAD_SHOP;

CREATE TABLE `USUARIO` (
  `ID_USUARIO` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(45) DEFAULT NULL,
  `APELLIDO` varchar(45) DEFAULT NULL,
  `NOMBRE_APODO` varchar(45) DEFAULT NULL,
  `PASS` varchar(45) DEFAULT NULL,
  `ESTADO` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;


insert into `USUARIO`(`ID_USUARIO`,`NOMBRE`,`APELLIDO`,`NOMBRE_APODO`,`PASS`,`ESTADO`) values (1,'ADMIN','ADMIN','ADMIN','ADMIN','A');
